---
# tasks file for kernel-upgrade
- name: Installing GPG key for Enterprise Linux
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Installing EL repo
  yum:
    name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present
  tags:
    - kernel

- name: Upgrading the kernel
  yum:
    name: kernel-ml
    enablerepo: elrepo-kernel
    state: present
  tags:
    - kernel

- name: Rebooting the machine
  reboot:

- name: Fixing GRUB order to boot to the right kernel
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT'
    line: 'GRUB_DEFAULT=0'
  tags:
    - kernel

- name: Generating GRUB boot config
  shell: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
  tags:
    - kernel

- name: Rebooting
  reboot: