---
# tasks file for common
    - name: Installing Container Run Time
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Add Docker Repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/
    - name: Install Docker CE
      yum:
        name: docker-ce-18.06.1.ce
        state: present
    - name: Enable and Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Disable Swap
      shell: "swapoff -a"
    - name: Add Kubernetes Repo
      copy:
        dest: "/etc/yum.repos.d/kubernetes.repo"
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kube*
    - name: Disable SELinux
      shell: |
        setenforce 0
        sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    - name: Install Kubelet Kubeadm and Kubectl
      shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    - name: Enable and Start Kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
    - name: Set Net Bridge Parameters IPv6
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        sysctl_file: /etc/sysctl.d/k8s.conf
    - name: Set Net Bridge Parameters IPv4
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: yes