---
# tasks file for master

# Necessary for VPP installation

# - name: Update kubeadm configuration - disable the use of memory Huge Pages
#   blockinfile: 
#     dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#     block: |
#         Environment="KUBELET_EXTRA_ARGS=--feature-gates HugePages=false"

# - name: Restarting Kubelet
#   systemd:
#     name: kubelet
#     daemon_reload: yes
#     state: restarted

# TODO: validate  kubeadm network connectivity using kubeadm pull images before


# TODO: pass all relevant possible kubeadm parameters into ansible variables
- name: Running Kubeadm Init on Master
  shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version=1.13.3" #--pod-network-cidr=10.244.0.0/16" # --token-ttl 0 " --ignore-preflight-errors 'all'  --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output

- name: Recording kubeadm_output to file
  copy:
    content: "{{kubeadm_output.stdout}}"
    dest: /home/vagrant/kubeadm_output

- name: Fetch kubeadm output
  fetch:
    src: /home/vagrant/kubeadm_output
    dest: ./kubeadm_output
    flat: yes

- name: Create kube dir on vagrant home
  file: path="/home/vagrant/.kube" state=directory

- name: Setting Up Kubectl
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant

- name: Fetch kubectl config on hypervisor machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: admin.conf
    flat: yes
  