---
# tasks file for rke
- name: Getting VM IPs to deploy RKE...
  connection: local
  become: alex
  shell: for NODE in master node1; do vagrant ssh -c "ip address | grep 'inet 192.168.121.' | cut -c10-24 | sed 's/\///'" $NODE 2>null; done
  register: vm_ips
  tags: test_rke

- name: Printing IP list...
  debug:
    var: vm_ips.stdout_lines
  tags: test_rke

- name: Updating Cluster yml with IP addresses
  connection: local
  become: alex
  blockinfile: 
    dest: ./roles/rke/files/cluster.yml
    block: | 
        nodes:
            - address: "{{ vm_ips.stdout_lines[0] }}"
              port: "22"
              role:
                - controlplane
                - etcd
              user: vagrant
              ssh_key_path: /home/alex/projects/kubeadm-ansible/.vagrant/machines/master/libvirt/private_key
            - address: "{{ vm_ips.stdout_lines[1] }}"
              port: "22"
              role:
                - worker
              user: vagrant
              ssh_key_path: /home/alex/projects/kubeadm-ansible/.vagrant/machines/node1/libvirt/private_key
              # There are several network plug-ins that work, but we default to canal      
        network:
            plugin: none
        # Currently only nginx ingress provider is supported.
        # To disable ingress controller, set `provider: none`
        ingress:
            provider: none
        dns:
            provider: coredns
  tags: test_rke

- name: Deploying rke cluster
  connection: local
  become: alex
  shell: "rke up --config ./roles/rke/files/cluster.yml --update-only"
  tags: test_rke