---
# tasks file for contiv-vpp

- name: Taking eth1 down and out of kernel control
  shell: "ip link set eth1 down"

- name: Loading the DPDK kernel module uio
  modprobe:
    name: uio_pci_generic
    state: present

- name: Creating the VPP directory
  file:
    path: "/etc/vpp/"
    state: directory

- name: Creating blank config file
  file:
    path: "/etc/vpp/contiv-vswitch.conf"
    state: touch

- name: Configuring eth1 to be used by DPDK
  blockinfile:
    dest: "/etc/vpp/contiv-vswitch.conf"
    block: |
        unix {
            nodaemon
            cli-listen /run/vpp/cli.sock
            cli-no-pager
            coredump-size unlimited
            full-coredump
            poll-sleep-usec 100
        }
        nat {
            endpoint-dependent
            translation hash buckets 1048576
            translation hash memory 268435456
            user hash buckets 1024
            max translations per user 10000
        }
        acl-plugin {
          use tuple merge 0
        }
        dpdk {
            dev 0000:00:06.0
        }
        api-trace {
          on
          nitems 5000
        }

- name: Deploying Contiv-vpp
  shell: kubectl apply -f /vagrant/contiv-vpp.yaml #https://raw.githubusercontent.com/contiv/vpp/master/k8s/contiv-vpp.yaml
  become_user: vagrant
  tags:
    - contiv